services:
  - type: web
    name: telegram-spinbot
    env: python
    buildCommand: ""
    startCommand: python main.py
    plan: free
    envVars:
      - key: TOKEN
        value: your_bot_token_here
